"""Write docs/GRAPH.md: the hand-written guide (docs/GRAPH.head.md) plus a reference section
generated from the registry in source_pipeline/graph_model.py and the ontology, so the
documented model cannot drift from the one the build enforces."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from source_pipeline import common  # noqa: E402
from source_pipeline.graph_model import ENTITY_TYPES, RELATIONS  # noqa: E402

ont = common.load_yaml(ROOT / "config" / "graph_ontology.yaml")
ents = "\n".join(f"| `{t}` | `{'`, `'.join(s['prefix'])}` | {s['meaning']} |" for t, s in ENTITY_TYPES.items())
rels = "\n\n".join(
    f"### `{r}`\n\n*{s['reads']}*{' (symmetric: stored once per pair)' if s.get('symmetric') else ''}\n\n"
    f"- **Meaning:** {s['semantics']}\n- **Assertion:** {s['assertion']}\n"
    f"- **Evidence required:** {s['evidence']}\n- **Confidence:** {s['confidence']}"
    for r, s in RELATIONS.items())
conc = "\n".join(f"| {sec} | {len(ont[sec])} | {', '.join(c['id'] for c in ont[sec])} |"
                 for sec in ("technologies", "capabilities", "use_cases"))
conf = "\n".join(f"| `{k}` | {v} |" for k, v in ont["confidence"].items())
ref = f"""

## Reference (generated by scripts/graph_docs.py; do not edit by hand)

### Entity types

| Type | Id prefix | Meaning |
|---|---|---|
{ents}

## Relationship types

Direction is always `from -> to` as written.

{rels}

### Ontology concepts (`config/graph_ontology.yaml`, reviewed {ont['reviewed_at']})

| Section | Count | Concepts |
|---|---|---|
{conc}

| Route | Confidence |
|---|---|
{conf}
"""
(ROOT / "docs" / "GRAPH.md").write_text((ROOT / "docs" / "GRAPH.head.md").read_text() + ref)
print("wrote docs/GRAPH.md")
