"""Write docs/SCORING-ACCEPTANCE.md: KEI-806 criterion by criterion, from the built scores.

Every figure is read from data/score/, never typed by hand.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
S = ROOT / "data" / "score"
summary = json.loads((S / "summary.json").read_text())
report = json.loads((S / "reports" / "validation_report.json").read_text())
cal = json.loads((S / "reports" / "calibration.json").read_text())
probe_path = ROOT / "evidence" / "KEI-806-refresh-probe.json"
probe = json.loads(probe_path.read_text()) if probe_path.exists() else None
records = {json.loads(l)["canonical"]: json.loads(l) for l in open(S / "records.jsonl")}
fits = [json.loads(l) for l in open(S / "replacement_fit.jsonl")]
health = {json.loads(l)["canonical"]: json.loads(l) for l in open(S / "project_health.jsonl")}


def ck(criterion):
    return "\n".join(f"- `{c['id']}` **{'PASS' if c['ok'] else 'FAIL'}**: "
                     f"`{json.dumps(c['detail'], sort_keys=True)[:300]}`"
                     for c in report["checks"] if c["criterion"].split("/")[0] == criterion)


def fmt(x):
    return f"{x:,}" if isinstance(x, int) else str(x)


def rec_example(canonical):
    r = records[canonical]
    h = health[canonical]
    lines = [f"**{r['name']}** ({r['url']}), evaluated {r['evaluated_at']}, score version {r['score_version']}", "",
             f"- Project Health **{r['project_health']['score']}/100 · {r['project_health']['band']}** · trajectory "
             f"**{r['trajectory']}** · Evidence Confidence **{r['evidence_confidence']}/100**"]
    for f in r["replacement_fit"]:
        lines.append(f"- Replacement Fit for {f['saas_name']}: **{f['score']}/100** (core gate {f['core_gate']}, "
                     f"confidence {f['confidence']}, credible: {f['credible_alternative']}, publish: {f['publish']})")
    for w in r["why"][:4]:
        lines.append(f"- why: {w['text']}  \n  `{w['evidence']}`")
    for d in r["disqualifiers"]:
        lines.append(f"- disqualifier `{d['id']}`: {d['reason']}  \n  `{d['evidence']}`")
    for w in r["watch_outs"]:
        lines.append(f"- watch-out `{w['id']}`: {w['detail']}")
    dims = " · ".join(f"{k.replace('_', ' ')} {v['score']}" for k, v in h["dimensions"].items())
    lines.append(f"- dimensions: {dims}")
    lines.append(f"- {r['endorsement']['statement']}")
    return "\n".join(lines)


def fit_table(rows):
    out = ["| Project | SaaS | Fit | Core | Gate | Confidence | Health | Credible | Publish |", "|---|---|---|---|---|---|---|---|---|"]
    for f in rows:
        out.append(f"| {f['canonical'].split('/', 1)[1]} | {f['saas_name']} | {f['score']} | {f['core_coverage']['score']} | "
                   f"{f['core_gate']} | {f['confidence']['score']} | {f['project_health_ref']['score']} | "
                   f"{'yes' if f['credible_alternative'] else ''} | {'yes' if f['publish'] else 'refused'} |")
    return "\n".join(out)


examples = [c for c in ("github.com/plausible/analytics", "github.com/authelia/authelia", "github.com/n8n-io/n8n")
            if c in records]
top = sorted((f for f in fits if f["credible_alternative"]), key=lambda f: -(f["score"] or 0))[:12]
by_p = {}
for f in fits:
    by_p.setdefault(f["canonical"], []).append(f)
spread = sorted(((p, fl) for p, fl in by_p.items() if len(fl) >= 2),
                key=lambda x: -(max(f["score"] or 0 for f in x[1]) - min(f["score"] or 0 for f in x[1])))[:3]
gated = [f for f in fits if f["core_gate"] == "failed"][:6]
cal_rows = "\n".join(f"| {c['group']} | {c['subject'][:70]} | {'met' if c['ok'] else '**missed**'} | "
                     f"`{json.dumps(c['detail'], sort_keys=True)[:160]}` |" for c in cal["results"])
n = summary

doc = f"""# KEI-806 acceptance: Project Health and Replacement Fit scoring

Generated by `scripts/score_acceptance.py` from `data/score/`. Score version
**{n['score_version']}**, evidence as of **{n['evidence_as_of']}**. Method: [SCORING.md](SCORING.md).
Validation: **{sum(c['ok'] for c in report['checks'])}/{len(report['checks'])} checks pass**.

| | |
|---|---|
| Projects scored (Project Health) | {fmt(n['projects_scored'])} |
| SaaS relationships scored (Replacement Fit) | {fmt(n['pairs_scored'])} |
| Credible alternatives | {fmt(n['credible_alternatives'])} |
| Mappings publishable / refused | {fmt(n['mappings_publishable'])} / {fmt(n['pairs_scored'] - n['mappings_publishable'])} |
| Recommendation-eligible projects | {fmt(n['recommendation_eligible'])} |
| Projects with a hard disqualifier | {fmt(n['disqualified'])} |
| Health bands | {', '.join(f'{k} {fmt(v)}' for k, v in sorted(n['bands'].items(), key=lambda x: str(x[0])))} |
| Trajectory | {', '.join(f'{k} {fmt(v)}' for k, v in sorted(n['trajectory'].items()))} |

Automatic scoring throughout. Nothing here is Keith-tested, Keith-endorsed or an editorial recommendation.

## Criterion by criterion

**1. Project Health is documented and machine-reproducible for every qualified retained OSS project.**
{ck('AC1')}

**2. Replacement Fit is documented and machine-reproducible only for projects with a credible SaaS relationship edge.**
{ck('AC2')}

**3. Source evidence for each score is inspectable and provenance-linked.**
{ck('AC3')}

**4. A healthy project can still score low on replacement fit and vice versa.**
{ck('AC4')}

**5. Confidence is represented separately from score.**
{ck('AC5')}

**6. Automatic scoring is never presented as Keith-tested/Keith-endorsed.**
{ck('AC6')}

**7. Low-confidence mappings can be refused from publication without excluding an otherwise useful Discover-lane project.**
{ck('AC7')}

**8. At least 60 candidate replacement relationships across the initial SaaS set are scored.**
{ck('AC8')}

**9. A representative Discover-only sample is Project-Health scored without inventing replacement edges.**
{ck('AC9')}

**10. Thresholds for "credible alternative", project-health status and recommendation eligibility are explicit and testable.**
{ck('AC10')}

**11. Scoring can be rerun against refreshed metadata without changing the schema or website/extension code.**
{ck('AC11')}

**12. Score history or score-relevant observations can be retained over time rather than only overwriting the latest value.**
{ck('AC12')}

### Rubric rules
{ck('R1')}
{ck('R2')}
{ck('R3')}
{ck('R4')}
{ck('R6')}

## Calibration set

Expectations written before the first full run (`config/score_calibration.yaml`).
{ck('calibration')}

| Group | Subject | Result | Detail |
|---|---|---|---|
{cal_rows}

## Example records

""" + "\n\n".join(rec_example(c) for c in examples) + f"""

## Strongest credible alternatives

{fit_table(top)}

## Same project, different incumbents (Fit is SaaS-pair specific)

""" + "\n\n".join(fit_table(fl) for _, fl in spread) + f"""

## Core gate in action (strong secondaries, core job not evidenced)

{fit_table(gated)}

## Refresh probe (AC11/AC12)

""" + (f"""`scripts/score_refresh_probe.py` re-observed {len(probe['sample'])} repositories under a new as_of
(**{probe['previous_as_of']} → {probe['refreshed_as_of']}**) in an isolated copy, rebuilt with unchanged
code and schema, validated {fmt(probe['records_validated'])} records ({len(probe['schema_errors'])} schema errors), and
the history now holds both evaluations of every sampled project: result **{'PASS' if probe['ok'] else 'FAIL'}**.
""" if probe else "Not run.\n")

(ROOT / "docs" / "SCORING-ACCEPTANCE.md").write_text(doc)
print("wrote docs/SCORING-ACCEPTANCE.md")
